apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
spec:
  isCA: true
  commonName: $(nvidiaRuntimeHookServiceName).$(nvidiaRuntimeHookNamespace).svc
  dnsNames:
  - $(nvidiaRuntimeHookServiceName).$(nvidiaRuntimeHookNamespace).svc
  - $(nvidiaRuntimeHookServiceName).$(nvidiaRuntimeHookNamespace).svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: nvidia-runtime-webhook-certs

---

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
