apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: admission-webhook
        args:
        - --tlscert=/etc/webhook/certs/tls.crt
        - --tlskey=/etc/webhook/certs/tls.key
