apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
    - v1beta1
    - v1
  clientConfig:
    caBundle: ""
    service:
      name: service
      path: /mutate/pods
  sideEffects: None
  failurePolicy: Ignore
  name: $(nvidiaRuntimeHookDeploymentName).xr.gs
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
